version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db_hospitalbi
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
  db :
    image: postgres
    container_name: dbpostgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_hospitalbi
    volumes:
      - datapg:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  datapg: